### ISSUE TITLE
rework Recall (Unison, Mono), implement Mono key events

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#1314]
- [x] create proper preset message consumption of Unison and Mono groups (#1295, #1305)
- [x] implement full Velocity range (from 4095 to 16383, #1285)
- [x] confirm LPC transmissons (HW Sources, Key Velocities, #1279) on Test Device
- [x] implement Mono KeyEvent handling
- [x] implement new FB Mixer Drive Scaling (#1319)
- [x] maintain parameter candidate definitions (#1304)

**Comment by MatthiasSeeber** [comment]
- verbleibender Check kann nach erfolgreichem Test am Gerät (14 Bit Velocities und HW Sources klappen bis 100%), wodurch dieses Issue geschlossen werden kann
