### ISSUE TITLE
General Update Procedure

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/C15#1735]
A small bunch of update script fixes:

- [x] Instead of naming the update steps (Rt-System // BBB // ePC) we are going to print out the process of the update (something like "1/5 done!" or a loading bar) --> #1866
- [x] Check if the update is even possible. The C15 might be running a windows system, which is not ready for 1.7! --> #1866
- [x] Force the User to Reboot/Restart the C15 after the update. Just found out, that the LPC needs a hard power down after an update. Thanks Klaus! --> #1866
- [x] chmod +x the executables just in case --> #1866
- [x] rsync seems to clear the journal, we should find a way which would not leave too much crap on the BBB but at the same time allows to look into the past ... --> #1869
- [x] when updating from 1.5 to 1.7 sda4 seems to be (sometimes!?) damaged and is not mounted to /dev/sda4 -> workaround: manually `mkfs.ext4 /dev/sda4` --> #1995
- [x] when updating from 1.5 to 1.7, the DeviceName changes, although the original SSID remains. --> @schlenkibus, will #1870 solve this?
- [x] C15 loads Preset banks first, before starting the update --> #1871 
- [x] Only rename the update.tar if the update was successful --> #1933
- [x] Put mxli (LPC) in to the updates and use it from there --> #1928
- [x] Once it's only one blob for the LPC, rework the update part in run.sh. (once #1936 is merged) This seems to cause LPC dropouts when the C15 starts
- [x] Always stop services if the update is to be run --> #1964  https://github.com/nonlinear-labs-dev/C15/blob/f390f97d024cd1684ee0387f3d1dc0f1fc082cb5/build-tools/create-c15-update/update_scripts/run.sh#L224
- [x] Add "Startting Update" after the Conditions check --> #1964

**Comment by majjam** [comment]
I would prefer to see anything like this :
1/5 : updating rt 
1/5 : rt -> ok
2/5 : updating bbb
2/5 : bbb -> ok
...

loading bars are always hard to communicate if something goes wrong.
Things like "it stopped by around a 3rd of the loading bar" aren't always helpful.
(my two cents)

**Comment by schlenkibus** [comment]
I agree that the user should be able to tell what went wrong (if that happens) but also i think the user should not necessarily see our internal descriptions of the subsystems, maybe we can think of user displayable names like, Audio Engine, User Interface (BBBB & Playground & NonMaps), Firmware (LPC) should be used. That means names that are common and not too abbreviated like RT and BBB.

**Comment by majjam** [comment]
@Schlenkibus : 
You are right, the stage names shouldn't be too techi for the end user.

**Comment by schlenkibus** [comment]
Regarding the last bullet point: Anton and I found out that the bbbb.service in 1.7 no longer waits for install-update-from-usb.service which should be the case
