### ISSUE TITLE
Todo Matthias

### ISSUE THREAD

**Issue by MatthiasSeeber** [nonlinear-labs-dev/C15#2940]
### Preparation
- [x] create exemplary Todolist Milestone and Label
- [x] create this exemplary Todolist Ticket

### Tests
- [x] reference a specific discussion #2553 (nice that this tag-based approach also works for discussions)
- [x] reference a specific [wiki](https://github.com/nonlinear-labs-dev/C15/wiki/C15-Build-Dependencies) (this is only possible with hyperlink)

### actual todo stuff
- [ ] PR #2916 ([Synth Engine Upd. 22](https://github.com/nonlinear-labs-dev/C15/milestone/14))
*(several parameter enhancements: modulateables, param ranges, info texts, ...)*
- [ ] ...

**Comment by MatthiasSeeber** [comment]
By using `Github flavored Markdown`([gfm](https://github.github.com/gfm/)), I can create a **todo list** with *checkboxes*, that can be easily maintained (actually checking the checkbox via mouse is possible). I can reference related issues, pull requests and discussions via the `hash` mechanism (`#2940` -> #2940) or link to other related urls.

I would be careful with discussing specific progress here in the comments, maybe a discussion would serve that purpose better?

**Comment by MatthiasSeeber** [comment]
This ticket was exploring a concept of bringing more transparency into individual progress/todo overviews. However, the consensus is that Github Discussions (and Projects) are much better suited for this, so the ticket-, and milestone concept can be removed.
